# Generated by Django 2.0.6 on 2018-06-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsBbc',
        ),
        migrations.DeleteModel(
            name='NewsIbt',
        ),
        migrations.DeleteModel(
            name='NewsReuters',
        ),
    ]
