# Generated by Django 2.0.6 on 2018-06-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0003_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='place',
        ),
    ]
